cp_network_aws:
  name: network-7a9da14a-977c-4100-988e-91867007a3b4
  namespace: 7a9da14a-977c-4100-988e-91867007a3b4

  providerConfigName: a6ae52c4-a029-4f9d-83e5-347a08b97f86

  network:
    region: us-west-1
    name: vpc-7a9da14a-977c-4100-988e-91867007a3b4
    cidrBlock: 10.10.10.0/24
    ngw: single # single | multi
    subnetPrivate:
    - cidrBlock: 10.10.10.0/28
      az: us-west-1b  # us-west-1 s√≥ tem b e c
    - cidrBlock: 10.10.10.16/28
      az: us-west-1b
    - cidrBlock: 10.10.10.32/28
      az: us-west-1c
    subnetPublic:
    - cidrBlock: 10.10.10.48/28
      az: us-west-1b
    - cidrBlock: 10.10.10.64/28
      az: us-west-1b
    - cidrBlock: 10.10.10.80/28
      az: us-west-1c
    eksName: jonathans-cluster

  tags:
  - key: "Env"
    value: dev
