# Default values for cp_eks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cp_eks:
  namespace: 7a9da14a-977c-4100-988e-91867007a3b4
  providerConfigName: 1e11519d-b6c5-4eb1-a823-fe43881307e1

  eks:
    name: jonathans-cluster
    region: us-west-1
    version: "1.23"
    endpointPrivateAccess: false
    endpointPublicAccess: true

  network:
    subnetIds:
    - "subnet-0a81feeda859c93f2"
    - "subnet-094b0f5b697dfa4df"
    - "subnet-0cd473fa08750d1f7"

  nodeGroups:
    - name: ngmgm
      minSize: 3
      maxSize: 3
      desiredSize: 3
      instanceTypes:
      - m5.large
      amiType: AL2_x86_64
      capacityType: ON_DEMAND
      labels:
        nodegroup: management
        env: dev
