name: network-7a9da14a-977c-4100-988e-91867007a3b4
namespace: 7a9da14a-977c-4100-988e-91867007a3b4

providerConfigName: a8252daa-4d2c-49d2-815a-dcd18ce0c204

network:
  region: us-west-1
  name: vpc-7a9da14a-977c-4100-988e-91867007a3b4
  cidrBlock: 10.10.10.0/24
  ngw: single # single | multi
  subnetPrivate:
  - cidrBlock: 10.10.10.0/28
    az: us-west-1b  # us-west-1 s√≥ tem b e c
  - cidrBlock: 10.10.10.16/28
    az: us-west-1b
  - cidrBlock: 10.10.10.32/28
    az: us-west-1c
  subnetPublic:
  - cidrBlock: 10.10.10.48/28
    az: us-west-1b
  - cidrBlock: 10.10.10.64/28
    az: us-west-1b
  - cidrBlock: 10.10.10.80/28
    az: us-west-1c
  eksName: jonathans-cluster

tags:
- key: "Env"
  value: dev
