# Default values for cp_eks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cp_eks:
  namespace: 7a9da14a-977c-4100-988e-91867007a3b4
  providerConfigName: 1c089d0a-3042-4784-b6d0-ad8f600138b3

  eks:
    name: jonathans-cluster
    region: us-west-1
    version: "1.23"
    endpointPrivateAccess: false
    endpointPublicAccess: true

  network:
    subnetIds:
    - "subnet-0225f29ed6b98451c"
    - "subnet-0471c67ad0bdf7c07"
    - "subnet-03377b2f3c2e0cfdf"

  nodeGroups:
    - name: ngmgm
      minSize: 3
      maxSize: 3
      desiredSize: 3
      instanceTypes:
      - m5.large
      amiType: AL2_x86_64
      capacityType: ON_DEMAND
      labels:
        nodegroup: management
        env: dev
